---
title: "Milestone5"
author: "Mengxi Tan"
date: "10/18/2019"
output: html_document
---

**About this document**
This file is used for 
1) cleaning and reading raw data.
2) create certain non-interactive graphs for the final display


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#When installing package data.table, choose "No compliation" method

library(readxl)
library(skimr)
library(ggplot2)
library(readxl)
library(janitor)
library(gifski)
library(gganimate)
library(data.table)
library(png)
library(plyr)
library(cowplot)
library(ggridges)
library(rstanarm)
library(broom)
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)
library(gt)
library(DT)
library(rgeos)
library(fuzzyjoin)
library(moderndive)
library(tidyverse)

#####
#DATA LOADING: Homeland Security Part

# load the immigration by continent data
# clean up names and values
# filter out "Total" and "Unknown"

immigration_continent <- read_xlsx("raw_data/immigration_yearbook/Immigration_ByContinent.xlsx", na = c("", "NA")) %>%
  clean_names()%>%
  filter(region %in% c("Africa", "Asia", "Europe", "North America", "Oceania", "South America")) %>%
  mutate(year = as.integer(year))

# rename columns

setnames(immigration_continent, "immediate_relatives_of_u_s_citizens", "immediate_relatives")

setnames(immigration_continent, "family_sponsored_preferences", "family")

setnames(immigration_continent, "employment_based_preferences", "employment")

setnames(immigration_continent, "refugees_and_asylees", "refugee")

# create a long format for continent level data

immigration_continent_long <- immigration_continent %>%
      select(region, year, immediate_relatives, family,employment, diversity, refugee, other) %>%
      gather(key = "admission_class", value = "count", immediate_relatives: other)

# load the immigration by country data
# clean up names and values

immigration_country_2017 <- read_xlsx("raw_data/immigration_yearbook/2017_table10d.xlsx", na = c("", "NA")) %>%
  clean_names() %>%
  mutate(year = 2017)

immigration_country_2016 <- read_xlsx("raw_data/immigration_yearbook/2016_table10d.xlsx", na = c("", "NA")) %>%
  clean_names() %>%
  mutate(year = 2016)

immigration_country_2015 <- read_xlsx("raw_data/immigration_yearbook/2015_table10d.xlsx", na = c("", "NA")) %>%
  clean_names()%>%
  mutate(year = 2015)

immigration_country_2014 <- read_xlsx("raw_data/immigration_yearbook/2014_table10d.xlsx", na = c("", "NA")) %>%
  clean_names()%>%
  mutate(year = 2014)

immigration_country_2013 <- read_xlsx("raw_data/immigration_yearbook/2013_table10d.xlsx", na = c("", "NA")) %>%
  clean_names()%>%
  mutate(year = 2013)


immigration_country_2012 <- read_xlsx("raw_data/immigration_yearbook/2012_table10d.xlsx", na = c("", "NA")) %>%
  clean_names()%>%
  mutate(year = 2012)

immigration_country_2011 <- read_xlsx("raw_data/immigration_yearbook/2011_table10d.xlsx", na = c("", "NA")) %>%
  clean_names()%>%
  mutate(year = 2011)

immigration_country_2010 <- read_xlsx("raw_data/immigration_yearbook/2010_table10d.xlsx", na = c("", "NA")) %>%
  clean_names()%>%
  mutate(year = 2010)

immigration_country_2009 <- read_xlsx("raw_data/immigration_yearbook/2009_table10d.xlsx", na = c("", "NA")) %>%
  clean_names()%>%
  mutate(year = 2009)

immigration_country_2008 <- read_xlsx("raw_data/immigration_yearbook/2008_table10d.xlsx", na = c("", "NA")) %>%
  clean_names()%>%
  mutate(year = 2008)

immigration_country_2007 <- read_xlsx("raw_data/immigration_yearbook/2007_table10d.xlsx", na = c("", "NA")) %>%
  clean_names()%>%
  mutate(year = 2007)


#Combine the country tables together

immigration_country <- rbind(immigration_country_2007,
                             immigration_country_2008,
                             immigration_country_2009,
                             immigration_country_2010,
                             immigration_country_2011,
                             immigration_country_2012,
                             immigration_country_2013,
                             immigration_country_2014,
                             immigration_country_2015,
                             immigration_country_2016,
                             immigration_country_2017)

# clean up table
# convert year to integer for graphing later

immigration_country <- immigration_country %>%
                          filter(region_and_country_of_birth != "Total") %>%
                          drop_na %>%
                          mutate(year = as.integer(year))

# rename columns

setnames(immigration_country, "region_and_country_of_birth", "country")

setnames(immigration_country, "immediate_relatives_of_u_s_citizens", "immediate_relatives")

setnames(immigration_country, "family_sponsored_preferences", "family")

setnames(immigration_country, "employment_based_preferences", "employment")

setnames(immigration_country, "refugees_and_asylees", "refugee")

# "-" means 0, D means cannot disclose
# treat both as 0 in this case
# convert to numeric value

# family column

immigration_country$family <- revalue(immigration_country$family, c("-"= "0"))
immigration_country$family <- revalue(immigration_country$family, c("D"= "0"))
immigration_country$family <- as.numeric(immigration_country$family)

# employment column

immigration_country$employment <- revalue(immigration_country$employment, c("-"= "0"))
immigration_country$employment <- revalue(immigration_country$employment, c("D"= "0"))
immigration_country$employment <- as.numeric(immigration_country$employment)

# relative column
immigration_country$immediate_relatives <- revalue(immigration_country$immediate_relatives, c("-"= "0"))
immigration_country$immediate_relatives <- revalue(immigration_country$immediate_relatives, c("D"= "0"))
immigration_country$immediate_relatives <- as.numeric(immigration_country$immediate_relatives)

# diversity column

immigration_country$diversity <- revalue(immigration_country$diversity, c("-"= "0"))
immigration_country$diversity <- revalue(immigration_country$diversity, c("D"= "0"))
immigration_country$diversity <- as.numeric(immigration_country$diversity)

# refugee column

immigration_country$refugee <- revalue(immigration_country$refugee, c("-"= "0"))
immigration_country$refugee <- revalue(immigration_country$refugee, c("D"= "0"))
immigration_country$refugee <- as.numeric(immigration_country$refugee)

# other column

immigration_country$other <- revalue(immigration_country$other, c("-"= "0"))
immigration_country$other <- revalue(immigration_country$other, c("D"= "0"))
immigration_country$other <- as.numeric(immigration_country$other)

# create a long format for continent level data

immigration_country_long <- immigration_country %>%
      select(country, year, immediate_relatives, family,employment, diversity, refugee, other) %>%
      gather(key = "admission_class", value = "count", immediate_relatives: other)

# rearrange the order of categorical variables for labelling later

immigration_country_long$admission_class <- factor(immigration_country_long$admission_class, levels = c("diversity", "employment", "immediate_relatives", "family", "refugee", "other"))

# make a clean data directory

dir.create("clean_data")

######
#DATA LOADING: US Census Bureau Part
#load english speaking capability by continent

# english speaking: only takes into consideration population 5+
# employment status: only takes into consideration population 16+

english_by_continent  <- read_xlsx("raw_data/social_immigrants/english_by_continent.xlsx", na = c("", "NA")) %>% clean_names()

#load english speaking capability by country, for the top 10 country with most US immigrants

english_by_country <-
read_xlsx("raw_data/social_immigrants/english_by_country.xlsx", na = c("", "NA")) %>% clean_names()

# load unemployment by country, for the top 10 country with most US immigrants

employment_by_country <-
read_xlsx("raw_data/social_immigrants/employment_by_country.xlsx", na = c("", "NA")) %>% clean_names()

# adding columns to employment table

employment_by_country <- employment_by_country %>%
           mutate(population_in_labor_force = percentage_in_labor_force * total_number) %>%
           mutate(employment_population = population_in_labor_force - unemployment_population)
  
# write the clean data to csv

write.csv(immigration_country, file = "clean_data/immigration_country.csv", row.names = FALSE)
write.csv(immigration_continent, file = "clean_data/immigration_continent.csv", row.names = FALSE)
write.csv(immigration_country_long, file = "clean_data/immigration_country_long.csv", row.names = FALSE)
write.csv(immigration_continent_long, file = "clean_data/immigration_continent_long.csv", row.names = FALSE)
write.csv(english_by_continent, file = "clean_data/english_continent.csv", row.names = FALSE)
write.csv(english_by_country, file = "clean_data/english_country.csv", row.names = FALSE)
write.csv(employment_by_country, file = "clean_data/employment_country.csv", row.names = FALSE)

```


```{r investigation/graph making - testing for app.R}

# examine the top 10 countries with the most immigrants
# Mexico 
# China, People's Republic
# India 
# Philippines 
# Dominican Republic
# Cuba 
# Vietnam  
# Colombia
# Haiti
# Jamaica

top10 <- immigration_country %>%
          group_by(country) %>%
          summarize(total = sum(total)) %>%
          arrange(desc(total)) %>%
          head(10)

# filter out to be top 10 countries only

immigration_country_10 <- immigration_country %>%
  filter(country %in% top10$country)

# create the top 10 countries gif

gif <- 
ggplot(immigration_country_10, aes(x = reorder(country, -total), y = total, color = country, fill = country)) +
 geom_col(alpha = 0.75) +
 transition_time(year) +
 theme(legend.position = "none") +
 labs(title = "Immigration into US: {(frame_time)}", subtitle = "Among Top 10 Source Countries",
      y = "Immigrants", x = "",
      caption = "Data Source: US Homeland Security, rnaturalearth Library") +
 theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

#save the gif 

anim_save("images/top_10.gif", gif)

```



``` {r graph - world map trial}

# load worldmap

world <- ne_countries(scale = "medium", returnclass = "sf")
class(world)

# first, summarize total immigration over the 10 years

immigration_country_sum <- immigration_country %>%
  group_by(country) %>%
  summarize(total = sum(total))

# anti_join result in 36 records that are in immigration_country_sum but can't be mapped
# examine the 36 records

anti_join(immigration_country_sum, world, by = c("country" = "name_long"))

# prepare for cleaning
# first, define not in

`%notin%` <- Negate(`%in%`)

# filter out other/unknown country

immigration_country_sum_clean <- immigration_country_sum %>%
  filter(country %notin% c("All other countries", 
                           "All other countries 1", 
                           "All other countries1", 
                           "Unknown"))

# compared manually to update the country names
# not using fuzzy match here, since unmatch could be of political/historical events

anti_join(immigration_country_sum_clean, world, by = c("country" = "name_long")) %>%
  arrange(desc(total))

# first, rename the regions

immigration_country_sum_clean$country <- 
  revalue(immigration_country_sum_clean$country, 
          c("China, People's Republic" = "China",
            "Korea, South" = "Republic of Korea",
            "Burma" = "Myanmar",
            "Russia" = "Russian Federation",
            "Congo, Democratic Republic" = "Democratic Republic of the Congo",
            "Cote d'Ivoire" = "Côte d'Ivoire",
            "Laos" = "Lao PDR",
            "Congo, Republic" = "Republic of Congo",
            "Gambia" = "The Gambia",
            "Bosnia-Herzegovina" = "Bosnia and Herzegovina",
            "Cabo Verde" = "Cape Verde", 
            "Antigua-Barbuda" = "Antigua and Barbuda",
            "Saint Kitts-Nevis" = "Saint Kitts and Nevis",
            "Macau" = "Macao",
            "Netherlands Antilles" = "Netherlands",
            "Korea, North" = "Dem. Rep. Korea",
            "Brunei" = "Brunei Darussalam",
            "Guadeloupe" = "France",
            "Curacao" = "Netherlands",
            "Martinique" = "France",
            "Netherlands Antilles (former)" = "Netherlands",
            "Micronesia, Federated States" = "Federated States of Micronesia",
            "Sao Tome and Principe" = "São Tomé and Principe",
            "Virgin Islands, British" = "British Virgin Islands",
            "French Guiana" = "France"))

# then, reallocate certain regions according to population before/after politcial event
# "Soviet Union (former)": mainly Russia and Urkanie, 7473 to Ukraine, 25624 to Russia Federation
# "Czechoslovakia (former)": 2860 to Czech Republic, 1430 to Slovakia
# "Czechia":: 1232 to Czech Republic
# "Serbia and Montenegro 1":  11694 to Serbia
# "Serbia and Montenegro1": 2199 to Serbia
# "Serbia and Montenegro": 920 to Serbia
# "Serbia and Montenegro (former)" : 578 to Serbia

immigration_country_sum_clean <- immigration_country_sum_clean %>%
  mutate(total = ifelse(country == "Russian Federation", total + 25624, total))

immigration_country_sum_clean <- immigration_country_sum_clean %>%
  mutate(total = ifelse(country == "Ukraine", total + 7473, total))

immigration_country_sum_clean <- immigration_country_sum_clean %>%
  mutate(total = ifelse(country == "Czech Republic", total + 2860 + 1232, total))

immigration_country_sum_clean <- immigration_country_sum_clean %>%
  mutate(total = ifelse(country == "Slovakia", total + 1430, total))

immigration_country_sum_clean <- immigration_country_sum_clean %>%
  mutate(total = ifelse(country == "Serbia", total + 11694 + 2199 + 920 + 578, total))

# filter out the regions processed in the last chunk

immigration_country_sum_clean <- immigration_country_sum_clean %>%
  filter(country %notin% c("Soviet Union (former)",
                           "Czechoslovakia (former)",
                           "Czechia",
                           "Serbia and Montenegro 1",
                           "Serbia and Montenegro1",
                           "Serbia and Montenegro",
                           "Serbia and Montenegro (former)"))

# rename the immigration column

immigration_country_sum_clean <- immigration_country_sum_clean %>%
                  mutate(immigration = total)

# reexamine again to make sure data is clean

anti_join(immigration_country_sum_clean, world, by = c("country" = "name_long"))

# join data onto world map

world_immigration <- left_join(world, immigration_country_sum_clean, by = c("name_long" = "country"))

# prepare for the map making
# add one column for average, 
# add one column  for per 10,000 people

world_immigration <- world_immigration %>%
  mutate(immigration_avg = immigration/11) %>%
  mutate(immigration_percap = immigration_avg/(pop_est /10000))


# map out overall immigration status
# US color on map will be photoshopped out later

map_overall <- ggplot(data = world_immigration) +
          geom_sf(aes(fill = immigration)) +
          scale_fill_viridis_c(option = "plasma", trans = "sqrt") +
          labs(title = "Total Immigration into US", subtitle = "Annual Average 2007 - 2017, Top 5: Mexico, China, India, Philippines and Dominican Republic",
               caption = "Data Source: US Homeland Security, rnaturalearth Library",
               fill = "Immigrants")

# save image to file  

ggsave("images/map_overall.png", map_overall)

# map out perCap immigration status
# US will be photoshopped out later  

map_perCap <- ggplot(data = world_immigration) +
          geom_sf(aes(fill = immigration_percap)) +
          scale_fill_viridis_c(option = "plasma", trans = "sqrt") +
          labs(title = "US Immigrants per 10,000 People", subtitle = "Annual Average 2007 - 2017, Top 5: Guyana, Bhutan, Grenada, Jamaica, Saint Kitts and Nevis",
               caption = "Data Source: US Homeland Security, rnaturalearth Library",
               fill = "per 10,000")

# save image to file   

ggsave("images/map_percap.png", map_perCap)
    
```

```{r regression}
english_country <- english_by_country
employment_country <- employment_by_country

social_combined <- left_join(employment_country, english_country, by = c("country", "year"))

immigration_country_regression <- immigration_country %>%
  mutate(work_visa_percent = employment/total) 

employment_country_regression <- employment_country %>%
  filter(country != "Korea, South") %>%
  mutate(employment_in_laborforce = 1- unemployment_rate_unemployed_labor_force)

english_country_regression <- english_country %>%
  filter(country != "Korea, South")

immigration_employment_combined <- left_join(employment_country_regression, immigration_country_regression, by = c("country", "year"))

immigration_language_combined <- left_join(english_country_regression, immigration_country_regression, by = c("country", "year"))


ggplot(immigration_employment_combined, mapping = aes(y = percentage_in_labor_force, x = work_visa_percent)) + 
     geom_point() +
     geom_smooth(method = "loess")
  
ggplot(immigration_employment_combined, mapping = aes(y = employment_in_laborforce, x = work_visa_percent)) + 
     geom_point() +
     geom_smooth(method = "loess")

ggplot(immigration_language_combined, mapping = aes(y = percentage_very_well, x = work_visa_percent)) + 
     geom_point() +
     geom_smooth(method = "loess")

ggplot(immigration_country, mapping = aes(y = work_visa_percent, x = family_visa_percent)) + 
     geom_point() +
     geom_smooth(method = "loess")

model <- lm(employment_in_laborforce ~ work_visa_percent, data = immigration_employment_combined)

model_table <- get_regression_table(model)

model_table2 <- glance(model)







```

